<div id="wrapper">
<table border="0" cellpadding="0" cellspacing="0" width="810">
  <tr>
   <td width="810" height="319">
   <?php echo Html::img('page2_r1_c1.png', '', array('width'=>810,'height'=>319, 'border' => 0))?>
  </td>
  </tr>
  <tr>
   <td><table align="left" border="0" cellpadding="0" cellspacing="0" width="810">
	  <tr>
	   <td width="535" height="44">
       <?php echo Html::img('page2_r2_c1.png', '', array('width'=>535,'height'=>44, 'border' => 0))?>
      </td>
	   <td><table align="left" border="0" cellpadding="0" cellspacing="0" width="148">
		  <tr>
		   <td width="148" height="28">
           <?php echo Html::img('page2_r2_c4.png', '', array('width'=>148,'height'=>28, 'id' => 'btn1', 'border' => 0))?>
           </td>
		  </tr>
		  <tr>
		   <td width="148" height="16">
           <?php echo Html::img('page2_r3_c4.png', '', array('width'=>148,'height'=>16, 'border' => 0))?>
         </td>
		  </tr>
		</table></td>
	   <td width="127" height="44">
       <?php echo Html::img('page2_r2_c6.png', '', array('width'=>127,'height'=>44, 'border' => 0))?>
       </td>
	  </tr>
	</table></td>
  </tr>
  <tr>
   <td><table align="left" border="0" cellpadding="0" cellspacing="0" width="810">
	  <tr>
	   <td><table align="left" border="0" cellpadding="0" cellspacing="0" width="782">
		  <tr>
		   <td><table align="left" border="0" cellpadding="0" cellspacing="0" width="782">
			  <tr>
			   <td width="438" height="190">
               <?php echo Html::img('page2_r4_c1.png', '', array('width'=>438,'height'=>190, 'border' => 0))?>
             </td>
			   <td><table align="left" border="0" cellpadding="0" cellspacing="0" width="344">
				  <tr>
				   <td width="344" height="29">
                   <?php echo Html::linkAction('choose',
				   Html::img('page2_r4_c3.png', '', array('width'=>344,'height'=>29, 'border' => 0)))?>
				   
                   </td>
				  </tr>
				  <tr>
				   <td width="344" height="161">
                   <?php echo Html::img('page2_r5_c3.png', '', array('width'=>344,'height'=>161, 'border' => 0))?>
                  </td>
				  </tr>
				</table></td>
			  </tr>
			</table></td>
		  </tr>
		  <tr>
		   <td><table align="left" border="0" cellpadding="0" cellspacing="0" width="782">
			  <tr>
			   <td width="115" height="19">
               <?php echo Html::img('page2_r6_c1.png', '', array('width'=>115,'height'=>19, 'border' => 0))?>
              </td>
			   <td width="539" height="19">
               
               <?php echo Html::linkAction('rules',  Html::img('page2_r6_c2.png', '', array('width'=>539,'height'=>19, 'border' => 0)));?>
               </td>
			   <td width="128" height="19">
               <?php echo Html::img('page2_r6_c5.png', '', array('width'=>128,'height'=>19, 'border' => 0))?>
              </td>
			  </tr>
			</table></td>
		  </tr>
		</table></td>
	   <td width="28" height="209">
       <?php echo Html::img('page2_r4_c7.png', '', array('width'=>28,'height'=>209, 'border' => 0))?>
       </td>
	  </tr>
	</table></td>
  </tr>
</table>
    
</div>

<?php View::partial('facebook_api') ?>