
<?php Tag::css('basic') ?>
<?php echo Html::includeCss() ?>

<div id="basic-modal-content">
    <div class="content_map">
            <?php echo Html::img('map.jpg')?>
        <div class="crown1">
            <?php echo Html::img('crown.png')?>
            <div class="message"><?php echo Html::img('complete_message.png')?></div>
        </div>
        <div class="crown2">
            <?php echo Html::img('crown.png')?>
            <div class="message"><?php echo Html::img('complete_message1.png')?></div>
        </div>
    </div>
</div>

<div style='display:none'>
    <img src='img/basic/x.png' alt='' />
</div>